version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres-api-pessoa
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Adm1n@23
      POSTGRES_DB: pessoas
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infra/scripts_sql:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "max_connections=1000"]
    networks: 
      my-network:
        ipv4_address: 172.21.0.2
  app:
    container_name: api-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks: 
      my-network:
        ipv4_address: 172.21.0.3
volumes:
  postgres-data:

networks: 
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16