version: '3'

services:
  # Node.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - postgres

  # PostgreSQL database
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Adm1n@23
      POSTGRES_DB: pessoas
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infra/scripts_sql:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "max_connections=1000"]
volumes:
  postgres-data:
