version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres-api-pessoa
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Adm1n@23
      POSTGRES_DB: pessoas
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: